// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oudqiqvsgovjmqbnfgzp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91ZHFpcXZzZ292am1xYm5mZ3pwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0Mzg1NzgsImV4cCI6MjA3MzAxNDU3OH0.8Eic4zF3b5F3NHg3lMDRJdoXynyMbgujKd4JPxQZo94";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});